### ISSUE TITLE
Sometimes logs get spammed with empty messages after a user connected/disconnected

### ISSUE THREAD

**Issue by Paddyk45** [Strawberry-Foundations/strawberry-chat#39] opened 2023-09-14 15:28 UTC
### Describe the bug

<img width="534" alt="image" src="https://github.com/Strawberry-Foundations/strawberry-chat/assets/73178245/de2cae36-fb42-48d4-b966-e760527de49c">

### Steps to reproduce

```bash
Join the server
```

### Chat Program

Server

### The version of Strawberry Chat you used

master

### Python Version

3.11

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This bug isn't fixed in the latest version of Strawberry Chat (including git)

**Comment by Juliandev02** [comment] 2023-09-14 17:45
I will test this later. Could be a bug that is caused by the readline libary.

**Comment by Juliandev02** [comment] 2023-09-29 19:46
For whatever reason, I have not been able to reproduce this error recently. I still leave this issue open in case there is something new. I wouldn't mark it as a false report, since I actually had this problem myself.

**Comment by Juliandev02** [comment] 2023-10-01 10:22
After some more tests, I still cannot reproduce this error. Closing this as not planned.

**Comment by Juliandev02** [comment] 2023-11-09 18:34
Finally fixed this issue with Commit https://github.com/Strawberry-Foundations/strawberry-chat/commit/7e70d83491c5a6cd83abf805fd89f94ba4d450f5

**Closed** 2023-11-09 18:35 UTC
Labels: bug, critical
